trigger:
- master
stages:  
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted VS2017
      demands:
      - msbuild
    steps:
    - script: 
        npm install
      displayName: 'npm install'
    - script:
        tsc
      displayName: 'compile'
    - script:
        npm test
      displayName: 'test'  
    - task: PRInsights@0
      displayName: Pull Request Insights