trigger:
- master
stages:  
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted VS2017
      demands:
      - msbuild
    steps:
    - powershell: |
        npm install
        npm install -g jest
      displayName: 'npm install'
    - powershell: 
        tsc
      displayName: 'compile'
    - powershell:
        npm test
      workingDirectory: .\pullRequestInsightsTask\
      displayName: 'test'  
    - task: PRInsights@0
      displayName: Pull Request Insights